Fix BigInteger out of range bug, cause of using long value.
reactor/reactor-addons pull request #284
Opened 2022-04-05 16:34 UTC by Sunshow

Previous version use number.longValue, and may be out of range, use String to fix it just like BigDecimal.

2022-04-05 16:35 UTC, pivotal-cla commented
@Sunshow Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/reactor?repositoryId=reactor/reactor-addons&pullRequestId=284)!

2022-04-07 08:58 UTC, Sunshow commented
@simonbasle just commit a new test case named `monoBigIntegerRange()`

2022-04-07 09:40 UTC, simonbasle commented
for reference: this is similar to #260 and #261

2022-04-07 09:47 UTC, simonbasle requested changes
looking good. one last comment around tests and this is good to merge from my perspective @Sunshow 👍

2022-04-07 09:47 UTC, simonbasle commented on reactor-extra/src/test/java/reactor/math/ReactorMathTests.java
> +	public void monoBigIntegerRange() {
rename to `noOverflowSumBigInteger` and split out the `averageBigInteger` case into `noOverflowAverageBigInteger()` (to be placed under the `emptyAverageBigInteger` one)

2022-04-07 14:07 UTC, simonbasle commented
if that's all good from your perspective @Sunshow I'll rebase on top of 3.4.x and merge in that branch (will need to do a force-push of your branch, FYI)

2022-04-07 14:14 UTC, Sunshow commented
> if that's all good from your perspective @Sunshow I'll rebase on top of 3.4.x and merge in that branch (will need to do a force-push of your branch, FYI)

That's ok, looking forward to the new release.

2022-04-07 15:11 UTC, simonbasle commented
I cannot rework the PR, either because you haven't authorized maintainers to modify your fork/PR or because this was opened from your fork's `main` branch. you will need to close that one and reopen a PR that applies the changes in a branch derived from `3.4.x` unfortunately, if you want this to ship in next week's 3.4.8 release 😞

2022-04-07 15:54 UTC, Sunshow commented
Complete the PR.

2022-04-08 11:55 UTC, Sunshow commented
> > Complete the PR.
> 
> I'm assuming you're asking me to add the fix in 3.4.x branch myself? I can do that and I think it makes sense.
> 
> Yet, let me know if you still want to contribute it.
> 
> In order to avoid the same confusion in the future, I would suggest always contributing PRs from feature branches (not a direct equivalent of the target maintenance branch) and making sure the "allow maintainers of the project to contribute to that PR" checkbox is checked.

My fault, that's my first PR, and I'm busy taking care of my babies, later I will learn how to continue.

2022-04-08 12:03 UTC, closed without merging

2022-04-08 12:12 UTC, simonbasle commented
that's no problem @Sunshow ! thanks for bringing the issue to our attention, in any case 🙇 👍  I will take care of that one, don't worry